-- Migration number: 0001 	 2023-04-30T15:49:10.528Z
-- Autogenerated by Superflare. Do not edit this file directly.
CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  published BOOLEAN NOT NULL,
  userId INTEGER NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);